## R-SPECIFIC: build data/cvxr_consensus.rda for the encrypted
## stratified Cox-lasso consensus-ADMM demonstration.
##
## The single source of truth is the vignette
## vignettes/cvxr-cox-lasso-dlbcl.Rmd: its code chunks ARE the pipeline,
## gated `eval = RECOMPUTE`. This script extracts those chunks with
## knitr::purl() (RECOMPUTE = TRUE un-gates them so they tangle as
## runnable code), writes them to inst/scripts/cvxr-consensus.R, sources
## that to run the fit once -- the expensive ~150-iteration ADMM is paid
## here -- and saves the result. Downstream documents then load
## data(cvxr_consensus) instead of recomputing, and the openfhe-jss
## manuscript reads the same purled chunks, so vignette, script,
## manuscript, and data object cannot drift.
##
## inst/scripts/cvxr-consensus.R is therefore a GENERATED artifact: do
## not edit it by hand; edit the vignette and re-run this script.
##
## Run from the package root with the OpenFHE environment the package is
## built against:
##   OPENFHE_HOME=.../temp/openfhe-rlibomp Rscript data-raw/cvxr_consensus.R

RECOMPUTE <- TRUE   # un-gate the eval=RECOMPUTE chunks when purling

script <- knitr::purl("vignettes/cvxr-cox-lasso-dlbcl.Rmd",
                      output = "inst/scripts/cvxr-consensus.R",
                      quiet  = TRUE)

## Prepend a provenance header to the generated script.
hdr <- c(
    "## GENERATED by data-raw/cvxr_consensus.R via knitr::purl() from",
    "## vignettes/cvxr-cox-lasso-dlbcl.Rmd. DO NOT EDIT BY HAND -- edit the",
    "## vignette and re-run data-raw/cvxr_consensus.R. This file is the",
    "## verbatim pipeline; sourcing it leaves `cvxr_consensus` in scope.",
    "")
writeLines(c(hdr, readLines(script)), script)

source(script)

stopifnot(is.list(cvxr_consensus),
          length(cvxr_consensus$agg_beta) == cvxr_consensus$params$K,
          cvxr_consensus$screen_match,
          cvxr_consensus$n_iter_ref < cvxr_consensus$params$MAX_ITER,
          cvxr_consensus$n_iter_enc < cvxr_consensus$params$MAX_ITER)

save(cvxr_consensus, file = "data/cvxr_consensus.rda", compress = "xz")
