#!/usr/bin/env bash
# sync_fixtures.sh — Regenerate and verify the cross-language parity
# fixtures that homomorphepy commits and ships.
#
# Usage, from anywhere:
#   bash data-raw/sync_fixtures.sh                 # regenerate + verify
#   bash data-raw/sync_fixtures.sh --verify-only   # verify what is on disk
#   bash data-raw/sync_fixtures.sh [...] <target>  # another fixtures dir
#
# The default target is the fixtures directory of a homomorphepy clone
# next to this one: ../homomorphepy/src/homomorphepy/fixtures. That
# directory is the single committed copy; commit it in homomorphepy
# after this script passes.
#
# Needs R with homomorpheR installed (the exporter reads the installed
# package's data) and uv (the verifier).
#
# STALENESS IS A HARD FAILURE. Files the exporter no longer writes are
# removed from the target, and the verifier must pass against the
# regenerated bytes, so a stale fixture cannot make a Python-vs-R parity
# failure look like a binding defect.

set -euo pipefail

PKG="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXPORTER="$PKG/data-raw/export_parity_fixtures.R"
VERIFIER="$PKG/data-raw/verify_parity_fixtures.py"

VERIFY_ONLY=false
TARGET=""
for arg in "$@"; do
    case "$arg" in
        --verify-only) VERIFY_ONLY=true ;;
        -*) echo "ERROR: unknown option: $arg" >&2; exit 1 ;;
        *)
            if [[ -n "$TARGET" ]]; then
                echo "ERROR: multiple targets: '$TARGET' and '$arg'" >&2; exit 1
            fi
            TARGET="$arg" ;;
    esac
done
TARGET="${TARGET:-$PKG/../homomorphepy/src/homomorphepy/fixtures}"
mkdir -p "$TARGET"
TARGET="$(cd "$TARGET" && pwd)"

if ! $VERIFY_ONLY; then
    echo "== regenerating fixtures from homomorpheR into $TARGET =="
    command -v Rscript >/dev/null || { echo "ERROR: Rscript not found" >&2; exit 1; }
    ( cd "$PKG" && Rscript "$EXPORTER" "$TARGET" )
    echo

    # Remove anything the manifest no longer lists.
    uv run --quiet --no-project python - "$TARGET" <<'PY'
import json, sys
from pathlib import Path
d = Path(sys.argv[1])
keep = {f["file"] for f in json.loads((d / "manifest.json").read_text())["files"]}
keep.add("manifest.json")
for p in sorted(d.iterdir()):
    if p.is_file() and p.name not in keep:
        p.unlink()
        print(f"  removed stale {p.name}")
PY
fi

[[ -f "$TARGET/manifest.json" ]] || {
    echo "ERROR: no manifest at $TARGET/manifest.json" >&2; exit 1; }

echo "== verifying $TARGET =="
command -v uv >/dev/null || { echo "ERROR: uv not found" >&2; exit 1; }
uv run --quiet --no-project --with numpy --with pandas python "$VERIFIER" "$TARGET"
