## GENERATED by data-raw/cvxr_consensus.R via knitr::purl() from
## vignettes/cvxr-cox-lasso-dlbcl.Rmd. DO NOT EDIT BY HAND -- edit the
## vignette and re-run data-raw/cvxr_consensus.R. This file is the
## verbatim pipeline; sourcing it leaves `cvxr_consensus` in scope.

## ----cvxr-libs, eval=RECOMPUTE------------------------------------------------
library(survival)
library(CVXR)
library(openfhe.R)
library(homomorpheR)


## ----cvxr-data, eval=RECOMPUTE------------------------------------------------
data(DLBCL,     package = "homomorpheR")  # 235 patients: survival + signatures
data(DLBCL_gex, package = "homomorpheR")  # 235 patients x 6416 Lymphochip probes
dlbcl <- DLBCL
dlbcl$Subgroup <- factor(dlbcl$Subgroup, levels = c("GCB","ABC","Type III"))
stopifnot(identical(as.character(dlbcl$ID), rownames(DLBCL_gex)))  # rows aligned

sites_raw <- lapply(levels(dlbcl$Subgroup), function(s) {
    idx <- which(dlbcl$Subgroup == s)
    list(name = s, X = DLBCL_gex[idx, ], time = dlbcl$time[idx],
         status = dlbcl$status[idx])
})
names(sites_raw) <- levels(dlbcl$Subgroup)
N_sites <- length(sites_raw)
N_total <- sum(vapply(sites_raw, function(s) nrow(s$X), 1L))
P_raw   <- ncol(DLBCL_gex)


## ----cvxr-standardize-plain, eval=RECOMPUTE-----------------------------------
pool_plain <- function(sites, n_total) {
    s <- Reduce(`+`, lapply(sites, function(s) colSums(s$X)))
    q <- Reduce(`+`, lapply(sites, function(s) colSums(s$X^2)))
    mu     <- s / n_total
    sigma2 <- pmax(q / n_total - mu^2, .Machine$double.eps)
    list(mu = mu, sigma = sqrt(sigma2))
}
pool      <- pool_plain(sites_raw, N_total)
sites_std <- lapply(sites_raw, function(s) list(
    name = s$name,
    X    = sweep(sweep(s$X, 2, pool$mu, "-"), 2, pool$sigma, "/"),
    time = s$time, status = s$status))


## ----cvxr-screen-plain, eval=RECOMPUTE----------------------------------------
K <- 100L

score_info_at_zero <- function(X, time, status) {
    p <- ncol(X)
    ord <- order(time, -status)
    X_o <- X[ord, , drop = FALSE]; stat_o <- status[ord]
    n <- nrow(X_o); U <- numeric(p); I <- numeric(p)
    for (i in seq_len(n)) {
        if (stat_o[i] == 1L) {
            risk <- X_o[i:n, , drop = FALSE]
            mu_R <- colMeans(risk)
            U <- U + (X_o[i, ] - mu_R)
            I <- I + colSums(sweep(risk, 2, mu_R, "-")^2) / nrow(risk)
        }
    }
    list(U = U, I = I)
}

screen_plain <- function(sites, K) {
    UI <- lapply(sites, function(s) score_info_at_zero(s$X, s$time, s$status))
    U  <- Reduce(`+`, lapply(UI, `[[`, "U"))
    I  <- Reduce(`+`, lapply(UI, `[[`, "I"))
    Z  <- U / sqrt(pmax(I, .Machine$double.eps))
    order(abs(Z), decreasing = TRUE)[seq_len(K)]
}
top_idx  <- screen_plain(sites_std, K)
sites_KS <- lapply(sites_std, function(s) list(
    name = s$name, X = s$X[, top_idx],
    time = s$time, status = s$status))
sigma_K  <- pool$sigma[top_idx]


## ----cvxr-centralized, eval=RECOMPUTE-----------------------------------------
LAMBDA <- 5
build_cox_breslow_nll <- function(beta_var, X_s, time_s, status_s) {
    ord <- order(time_s, -status_s)
    X_o <- X_s[ord, , drop = FALSE]; stat_o <- status_s[ord]
    n <- nrow(X_o); eta_o <- X_o %*% beta_var
    terms <- list()
    for (i in seq_len(n)) {
        if (stat_o[i] == 1L) {
            terms[[length(terms) + 1L]] <-
                log_sum_exp(eta_o[i:n, 1]) - eta_o[i, 1]
        }
    }
    Reduce(`+`, terms)
}

beta_var <- Variable(K, name = "beta")
nll_per  <- lapply(sites_KS, function(s)
    build_cox_breslow_nll(beta_var, s$X, s$time, s$status))
agg_prob <- Problem(Minimize(Reduce(`+`, nll_per) +
                                 LAMBDA * p_norm(beta_var, 1)))
suppressMessages(suppressWarnings(
    psolve(agg_prob, solver = "CLARABEL", verbose = FALSE)))
agg_beta <- as.numeric(value(beta_var))


## ----cvxr-local, eval=RECOMPUTE-----------------------------------------------
RHO <- 50

build_local <- function(X_k, time_k, status_k, rho) {
    p <- ncol(X_k)
    x  <- Variable(p); zp <- Parameter(p); up <- Parameter(p)
    nll <- build_cox_breslow_nll(x, X_k, time_k, status_k)
    aug <- (rho / 2) * sum_squares(x - zp + up)
    list(prob = Problem(Minimize(nll + aug)), x = x, zp = zp, up = up)
}
sites_problem <- lapply(sites_KS, function(s)
    build_local(s$X, s$time, s$status, RHO))


## ----cvxr-admm, eval=RECOMPUTE------------------------------------------------
MAX_ITER <- 200L; TOL <- 5e-3
soft_threshold <- function(v, tau) sign(v) * pmax(abs(v) - tau, 0)

run_admm <- function(sites_problem, consensus) {
    site_x <- replicate(N_sites, rep(0, K), simplify = FALSE)
    site_u <- replicate(N_sites, rep(0, K), simplify = FALSE)
    z_curr <- rep(0, K); trajectory <- list()
    for (iter in seq_len(MAX_ITER)) {
        for (i in seq_len(N_sites)) {
            value(sites_problem[[i]]$zp) <- z_curr
            value(sites_problem[[i]]$up) <- site_u[[i]]
            suppressMessages(suppressWarnings(
                psolve(sites_problem[[i]]$prob, solver = "CLARABEL",
                       verbose = FALSE)))
            site_x[[i]] <- as.numeric(value(sites_problem[[i]]$x))
        }
        w_avg  <- consensus(site_x, site_u)
        z_new  <- soft_threshold(w_avg, LAMBDA / (N_sites * RHO))
        site_u <- Map(function(u, x) u + (x - z_new), site_u, site_x)
        primal <- sqrt(mean(vapply(site_x, function(x) sum((x - z_new)^2), 0)))
        dual   <- RHO * sqrt(sum((z_new - z_curr)^2))
        z_curr <- z_new; trajectory[[iter]] <- z_new
        if (primal < TOL && dual < TOL) break
    }
    list(z = z_curr, trajectory = trajectory)
}

plain_consensus <- function(site_x, site_u)
    Reduce(`+`, Map(`+`, site_x, site_u)) / length(site_x)

ref   <- run_admm(sites_problem, plain_consensus)
z_ref <- ref$z


## ----cvxr-context, eval=RECOMPUTE---------------------------------------------
cc <- fhe_context("CKKS",
                  multiplicative_depth = 1L,
                  scaling_mod_size     = 59L,
                  first_mod_size       = 60L,
                  batch_size           = 8192L,
                  features             = c(Feature$MULTIPARTY))
master <- make_threshold_master("Aggregator",
                                crypto_context = cc, n_sites = N_sites)


## ----cvxr-pool-encrypt, eval=RECOMPUTE----------------------------------------
encrypt_pool <- function(master, sites, n_total, p_raw) {
    s_ct <- lapply(sites, function(s) master_encrypt(master, colSums(s$X)))
    q_ct <- lapply(sites, function(s) master_encrypt(master, colSums(s$X^2)))
    pooled_sum   <- master_decrypt(master, Reduce(`+`, s_ct), len = p_raw)
    pooled_sumsq <- master_decrypt(master, Reduce(`+`, q_ct), len = p_raw)
    mu     <- pooled_sum / n_total
    sigma2 <- pmax(pooled_sumsq / n_total - mu^2, .Machine$double.eps)
    list(mu = mu, sigma = sqrt(sigma2))
}
fhe_pool <- encrypt_pool(master, sites_raw, N_total, P_raw)


## ----cvxr-screen-encrypt, eval=RECOMPUTE--------------------------------------
encrypt_screen <- function(master, sites, p_raw, K) {
    enc <- function(v) master_encrypt(master, v)
    UI  <- lapply(sites, function(s) score_info_at_zero(s$X, s$time, s$status))
    U   <- master_decrypt(master, Reduce(`+`, lapply(UI, function(z) enc(z$U))),
                          len = p_raw)
    I   <- master_decrypt(master, Reduce(`+`, lapply(UI, function(z) enc(z$I))),
                          len = p_raw)
    Z   <- U / sqrt(pmax(I, .Machine$double.eps))
    order(abs(Z), decreasing = TRUE)[seq_len(K)]
}
fhe_top <- encrypt_screen(master, sites_std, P_raw, K)
stopifnot(setequal(fhe_top, top_idx))   # same probes as the plaintext screen


## ----cvxr-consensus, eval=RECOMPUTE-------------------------------------------
encrypted_consensus <- function(site_x, site_u) {
    cts    <- lapply(seq_along(site_x), function(i)
                  master_encrypt(master, site_x[[i]] + site_u[[i]]))
    ct_avg <- Reduce(`+`, cts) * (1 / length(site_x))
    master_decrypt(master, ct_avg, len = K)
}
fhe        <- run_admm(sites_problem, encrypted_consensus)
z_curr     <- fhe$z
trajectory <- fhe$trajectory


## ----cvxr-assemble, eval=RECOMPUTE, echo=FALSE--------------------------------
## (not shown in the rendered vignette; purled into the regeneration
## script) collect the primitives the vignette, manuscript, and data
## object share. Light derived quantities are recomputed downstream.
cvxr_consensus <- list(
    params     = list(K = K, LAMBDA = LAMBDA, RHO = RHO,
                      MAX_ITER = MAX_ITER, TOL = TOL),
    top_idx    = top_idx,
    sigma_K    = sigma_K,
    agg_beta   = agg_beta,
    z_ref      = z_ref,
    z_enc      = z_curr,
    trajectory = trajectory,
    n_iter_ref = length(ref$trajectory),
    n_iter_enc = length(trajectory),
    pool_agree = list(mu    = max(abs(fhe_pool$mu    - pool$mu)),
                      sigma = max(abs(fhe_pool$sigma - pool$sigma))),
    screen_match = setequal(fhe_top, top_idx))

