## R-SPECIFIC: roxygen documentation for the shipped DLBCL_gex dataset.
## (The companion DLBCL clinical/signature table is documented by the
## hand-written man/DLBCL.Rd.)

#' DLBCL Lymphochip gene-expression matrix
#'
#' Gene-expression profiles for the 235-patient DLBCL cohort of
#' Rosenwald et al. (2002), used as the high-dimensional benchmark
#' in the encrypted distributed Cox-lasso demonstration.
#'
#' @format A numeric matrix with 235 rows (patients) and 6416
#'   columns (Lymphochip microarray features). Row names are the
#'   patient LYM identifiers, matching `DLBCL$ID`; column names are
#'   the microarray UNIQIDs. Values are log-ratios on the original
#'   scale.
#'
#' @details
#' Derived from the public Lymphoma/Leukemia Molecular Profiling
#' Project release (<https://llmpp.nih.gov/DLBCL/>; files
#' `DLBCL_patient_data_NEW.txt` and `NEJM_Web_Fig1data`). Patients
#' are matched to expression columns by LYM number. Of the 7399
#' Lymphochip features, the 6416 measured across the cohort are
#' retained, and the sporadic remaining missing values are imputed
#' by the per-feature median (cf. Bayle, Fan and Lou, 2025); the
#' five patients with zero follow-up time are excluded, leaving 235
#' patients. Standardization is deliberately *not* baked into the
#' stored matrix --- it is performed inside the encrypted pipeline
#' so that the demonstration exercises encrypted standardization.
#' The full processing script is `data-raw/DLBCL.R`.
#'
#' @source Rosenwald A, Wright G, Chan WC, et al. (2002). The use of
#'   molecular profiling to predict survival after chemotherapy for
#'   diffuse large-B-cell lymphoma. *New England Journal of Medicine*
#'   346(25):1937--1947. Data: <https://llmpp.nih.gov/DLBCL/>.
#'
#' @seealso [DLBCL]
#' @keywords datasets
"DLBCL_gex"

#' Precomputed encrypted Cox-lasso consensus-ADMM results
#'
#' Result objects from the encrypted stratified Cox-lasso
#' consensus-ADMM demonstration on the [DLBCL] / [DLBCL_gex] cohort:
#' a centralized [CVXR][CVXR::CVXR-package] ground-truth fit, the same
#' fit recovered by consensus ADMM in the clear, and the encrypted
#' threshold-FHE fit that swaps only the consensus channel. The
#' ~150-iteration ADMM runs are expensive, so they are computed once
#' and shipped here; the manuscript and the `cvxr-consensus-admm`
#' vignette load this object instead of recomputing, and pull their
#' displayed code from the generating script (see Details).
#'
#' @format A named list with components
#' \describe{
#'   \item{params}{list of the run constants: `K` (screened probes,
#'     100), `LAMBDA` (L1 penalty, 5), `RHO` (ADMM penalty, 50),
#'     `MAX_ITER` (200), `TOL` (5e-3).}
#'   \item{top_idx}{integer vector of length `K`; column indices into
#'     `DLBCL_gex` of the top-`K` univariate-screened probes.}
#'   \item{sigma_K}{numeric vector of length `K`; pooled standard
#'     deviations of the screened probes, for the back-transform to
#'     the original scale.}
#'   \item{agg_beta}{numeric vector of length `K`; centralized CVXR
#'     Cox-lasso coefficients (the ground truth), on the standardized
#'     scale.}
#'   \item{z_ref}{numeric vector of length `K`; consensus-ADMM
#'     coefficients computed in the clear (plaintext reference).}
#'   \item{z_enc}{numeric vector of length `K`; consensus-ADMM
#'     coefficients under threshold FHE.}
#'   \item{trajectory}{list of numeric vectors of length `K`; the
#'     encrypted consensus iterate \eqn{z^t} at each ADMM iteration.}
#'   \item{n_iter_ref, n_iter_enc}{iterations to convergence for the
#'     plaintext and encrypted runs.}
#'   \item{pool_agree}{list `mu`, `sigma`: max absolute disagreement
#'     between the encrypted and plaintext pooled standardization
#'     moments.}
#'   \item{screen_match}{logical; whether the encrypted screen selected
#'     the same probe set as the plaintext screen.}
#' }
#'
#' @details
#' Generated by `data-raw/cvxr_consensus.R`, which sources the
#' canonical pipeline `inst/scripts/cvxr-consensus.R`. That script is
#' the single source of truth: its labelled chunks are read verbatim
#' (via [knitr::read_chunk()]) by the openfhe-jss manuscript and the
#' `cvxr-consensus-admm` vignette, so the code displayed there is
#' exactly the code that produced these results. Find the installed
#' copy with
#' `system.file("scripts", "cvxr-consensus.R", package = "homomorpheR")`.
#'
#' @seealso [DLBCL], [DLBCL_gex]
#' @keywords datasets
"cvxr_consensus"
